version: '3.8'

volumes:
  production_traefik: {}
  postgres_data: {}

services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=canteen
      - POSTGRES_DB=canteen

  frontend:
    container_name: frontend
    image: nurecanteen_production_frontend
    build:
      context: .
      dockerfile: ./compose/production/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    container_name: backend
    image: nurecanteen_production_backend
    build:
      context: .
      dockerfile: ./compose/production/backend/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    command: /start_backend

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: nurecanteen_production_traefik
    depends_on:
      - frontend
      - backend
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
